services:
  app:
    container_name: rare-book-app
    image: rare-book-api:latest
    environment:
      - SPRING_SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/rarebooks?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration/mysql
      - SPRING_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    ports:
      - "8080:8080"
    networks:
      - rare_book_network
  mysql:
    container_name: rare-book-mysql
    image: mysql:8.0.3
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=rarebooks
      - MYSQL_USER=root
    volumes:
      - ./docker/volume_data/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - rare_book_network
  phpmyadmin:
    container_name: rare-book-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=rare-book-mysql
    ports:
      - "9090:80"
    networks:
      - rare_book_network

networks:
  rare_book_network: